name:                merger
version:             0.0.1.0
license:             NCSA
author:              "Thomas Tuegel"
maintainer:          "thomas.tuegel@runtimeverification.com"
copyright:           "2019 Runtime Verification Inc"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the [README](README.md) file.

dependencies:
  - base >= 4.7
  - exceptions
  - generic-lens
  - github
  - lens
  - mtl
  - vector

default-extensions:
  - BlockArguments
  - DuplicateRecordFields
  - NamedFieldPuns
  - OverloadedStrings

ghc-options: -fno-ignore-asserts

executables:
  merger:
    main: Main.hs
    source-dirs:
      - src
